baseurl: ""
domain: ""
url: "https://clyron.is-a.dev/lynxwebsite"
name: "Lynxmic"
logo: "/img/logotype.png"
currentyear: "2025"

discord: "wDxDKJU2sj"
source_url: "https://github.com/theclyron/lynxwebsite"
